/*
 * This file is generated by jOOQ.
 */
package br.com.kleverton.oliveira.skipthedishes.commons.jooq.tables.records;


import br.com.kleverton.oliveira.skipthedishes.commons.jooq.tables.OrdersProducts;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrdersProductsRecord extends UpdatableRecordImpl<OrdersProductsRecord> implements Record4<Long, Long, Long, Integer> {

    private static final long serialVersionUID = 44672816;

    /**
     * Setter for <code>skipthedishes.orders_products.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>skipthedishes.orders_products.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>skipthedishes.orders_products.id_order</code>.
     */
    public void setIdOrder(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>skipthedishes.orders_products.id_order</code>.
     */
    public Long getIdOrder() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>skipthedishes.orders_products.id_product</code>.
     */
    public void setIdProduct(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>skipthedishes.orders_products.id_product</code>.
     */
    public Long getIdProduct() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>skipthedishes.orders_products.quantity</code>.
     */
    public void setQuantity(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>skipthedishes.orders_products.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Long, Long, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Long, Long, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return OrdersProducts.ORDERS_PRODUCTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return OrdersProducts.ORDERS_PRODUCTS.ID_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return OrdersProducts.ORDERS_PRODUCTS.ID_PRODUCT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return OrdersProducts.ORDERS_PRODUCTS.QUANTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getIdOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getIdProduct();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getIdOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getIdProduct();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersProductsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersProductsRecord value2(Long value) {
        setIdOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersProductsRecord value3(Long value) {
        setIdProduct(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersProductsRecord value4(Integer value) {
        setQuantity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersProductsRecord values(Long value1, Long value2, Long value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrdersProductsRecord
     */
    public OrdersProductsRecord() {
        super(OrdersProducts.ORDERS_PRODUCTS);
    }

    /**
     * Create a detached, initialised OrdersProductsRecord
     */
    public OrdersProductsRecord(Long id, Long idOrder, Long idProduct, Integer quantity) {
        super(OrdersProducts.ORDERS_PRODUCTS);

        set(0, id);
        set(1, idOrder);
        set(2, idProduct);
        set(3, quantity);
    }
}
