/*
 * This file is generated by jOOQ.
 */
package br.com.kleverton.oliveira.skipthedishes.commons.jooq;


import br.com.kleverton.oliveira.skipthedishes.commons.jooq.tables.Accounts;
import br.com.kleverton.oliveira.skipthedishes.commons.jooq.tables.Orders;
import br.com.kleverton.oliveira.skipthedishes.commons.jooq.tables.OrdersProducts;
import br.com.kleverton.oliveira.skipthedishes.commons.jooq.tables.Products;
import br.com.kleverton.oliveira.skipthedishes.commons.jooq.tables.Restaurants;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Skipthedishes extends SchemaImpl {

    private static final long serialVersionUID = -1837737058;

    /**
     * The reference instance of <code>skipthedishes</code>
     */
    public static final Skipthedishes SKIPTHEDISHES = new Skipthedishes();

    /**
     * The table <code>skipthedishes.accounts</code>.
     */
    public final Accounts ACCOUNTS = br.com.kleverton.oliveira.skipthedishes.commons.jooq.tables.Accounts.ACCOUNTS;

    /**
     * The table <code>skipthedishes.orders</code>.
     */
    public final Orders ORDERS = br.com.kleverton.oliveira.skipthedishes.commons.jooq.tables.Orders.ORDERS;

    /**
     * The table <code>skipthedishes.orders_products</code>.
     */
    public final OrdersProducts ORDERS_PRODUCTS = br.com.kleverton.oliveira.skipthedishes.commons.jooq.tables.OrdersProducts.ORDERS_PRODUCTS;

    /**
     * The table <code>skipthedishes.products</code>.
     */
    public final Products PRODUCTS = br.com.kleverton.oliveira.skipthedishes.commons.jooq.tables.Products.PRODUCTS;

    /**
     * The table <code>skipthedishes.restaurants</code>.
     */
    public final Restaurants RESTAURANTS = br.com.kleverton.oliveira.skipthedishes.commons.jooq.tables.Restaurants.RESTAURANTS;

    /**
     * No further instances allowed
     */
    private Skipthedishes() {
        super("skipthedishes", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Accounts.ACCOUNTS,
            Orders.ORDERS,
            OrdersProducts.ORDERS_PRODUCTS,
            Products.PRODUCTS,
            Restaurants.RESTAURANTS);
    }
}
