/*
 * This file is generated by jOOQ.
 */
package br.com.kleverton.oliveira.skipthedishes.commons.jooq;


import br.com.kleverton.oliveira.skipthedishes.commons.jooq.tables.Accounts;
import br.com.kleverton.oliveira.skipthedishes.commons.jooq.tables.Orders;
import br.com.kleverton.oliveira.skipthedishes.commons.jooq.tables.OrdersProducts;
import br.com.kleverton.oliveira.skipthedishes.commons.jooq.tables.Products;
import br.com.kleverton.oliveira.skipthedishes.commons.jooq.tables.Restaurants;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in skipthedishes
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>skipthedishes.accounts</code>.
     */
    public static final Accounts ACCOUNTS = br.com.kleverton.oliveira.skipthedishes.commons.jooq.tables.Accounts.ACCOUNTS;

    /**
     * The table <code>skipthedishes.orders</code>.
     */
    public static final Orders ORDERS = br.com.kleverton.oliveira.skipthedishes.commons.jooq.tables.Orders.ORDERS;

    /**
     * The table <code>skipthedishes.orders_products</code>.
     */
    public static final OrdersProducts ORDERS_PRODUCTS = br.com.kleverton.oliveira.skipthedishes.commons.jooq.tables.OrdersProducts.ORDERS_PRODUCTS;

    /**
     * The table <code>skipthedishes.products</code>.
     */
    public static final Products PRODUCTS = br.com.kleverton.oliveira.skipthedishes.commons.jooq.tables.Products.PRODUCTS;

    /**
     * The table <code>skipthedishes.restaurants</code>.
     */
    public static final Restaurants RESTAURANTS = br.com.kleverton.oliveira.skipthedishes.commons.jooq.tables.Restaurants.RESTAURANTS;
}
